language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

addons:
  postgresql: "9.3"

before_script:
  - mysql -e "create database test;"
  - psql -c "create database test;" -U postgres

after_success:
  - gradle test
